### ISSUE TITLE
Does not build at all over 18000 errors

### ISSUE THREAD

**Issue by MrBananaGuard** [SapientGuardian/mysql-dnxcore50#3]

**Comment by SapientGuardian** [comment]
Yes, as covered in #1 this was built with early rc2 packages. As per aspnet/Announcements/issues/176 you can't use rc2 packages with dnx anymore. I'm working on a refresh of this project targeting netstandard1.5 ( https://github.com/SapientGuardian/mysql-connector-net-netstandard1.5 ) that can be built with the dotnet CLI. RC2 will be officially released this month, at which time I will publish a new package compatible with it.

If you really must have this now, there is a branch that can be built against rc2-update1 at https://github.com/SapientGuardian/mysql-dnxcore50/tree/rc1-update1

**Comment by MrBananaGuard** [comment]
Thanks for the feedback, the rc1 version works and builds first shot!
